endpoints:
  -
    name: homepage
    uri: '/'
    max_response_time: 0.09
    target_response_time: 0.05
  -
    name: New Users
    uri: '/users/new'
    max_response_time: 0.9
    target_response_time: 0.5
